# Generated by Django 6.1.1 on 2026-09-16 09:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do Insumo')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='budgets.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item de Material',
                'verbose_name_plural': 'Itens de Materiais',
            },
        ),
    ]
